tp-cooldown: 30

tp-delay: 5

tp-request-expiration: 30

tp-wild-max-radius: 3000

tp-wild-min-radius: 1500

random-locations-amount: 10000

toa: "Some really long text, use \\n to skip a line"

death-chance: 1